
#define QHTTP_METHOD_GET "GET"
#define QHTTP_METHOD_POST "POST"
#define QHTTP_METHOD_PATCH "PATCH"
#define QHTTP_METHOD_DELETE "DELETE"
#define HTTP_METHODS [QHTTP_METHOD_GET, QHTTP_METHOD_POST, QHTTP_METHOD_PATCH, QHTTP_METHOD_DELETE]
