
#define HTTP_METHOD_GET GET
#define HTTP_METHOD_POST POST
#define HTTP_METHOD_PATCH PATCH
#define HTTP_METHOD_DELETE DELETE
#define QHTTP_METHOD_GET QUOTE(HTTP_METHOD_GET)
#define QHTTP_METHOD_POST QUOTE(HTTP_METHOD_POST)
#define QHTTP_METHOD_PATCH QUOTE(HTTP_METHOD_PATCH)
#define QHTTP_METHOD_DELETE QUOTE(HTTP_METHOD_DELETE)
#define HTTP_METHODS [QHTTP_METHOD_GET, QHTTP_METHOD_POST, QHTTP_METHOD_PATCH, QHTTP_METHOD_DELETE]
