
class GVAR(checkbox) {
    type = 77;
    style = 0;
    checked = 0;
    color[] = {RGBA_PRIMARY_COLOR_DARK_TEXT};
    colorBackground[] = {RGBA_VOID_COLOR_EMPTY};
    colorBackgroundDisabled[] = {RGBA_VOID_COLOR_EMPTY};
    colorBackgroundFocused[] = {RGBA_VOID_COLOR_EMPTY};
    colorBackgroundHover[] = {RGBA_VOID_COLOR_EMPTY};
    colorBackgroundPressed[] = {RGBA_VOID_COLOR_EMPTY};
    colorDisabled[] = {RGBA_PRIMARY_COLOR_DISABLED_TEXT};
    colorFocused[] = {RGB_PRIMARY_COLOR_DARK_TEXT};
    colorHover[] = {RGB_PRIMARY_COLOR_DARK_TEXT};
    colorPressed[] = {RGB_PRIMARY_COLOR_DARK_TEXT};
    soundClick[] = {"", 0.1, 1};
    soundEnter[] = {"", 0.1, 1};
    soundEscape[] = {"", 0.1, 1};
    soundPush[] = {"", 0.1, 1};
    textureChecked = PATHOF(data\ui\checkbox-checked.paa);
    textureDisabledChecked = PATHOF(data\ui\checkbox-checked.paa);
    textureDisabledUnchecked = PATHOF(data\ui\checkbox-unchecked.paa);
    textureFocusedChecked = PATHOF(data\ui\checkbox-checked.paa);
    textureFocusedUnchecked = PATHOF(data\ui\checkbox-unchecked.paa);
    textureHoverChecked = PATHOF(data\ui\checkbox-checked.paa);
    textureHoverUnchecked = PATHOF(data\ui\checkbox-unchecked.paa);
    texturePressedChecked = PATHOF(data\ui\checkbox-checked.paa);
    texturePressedUnchecked = PATHOF(data\ui\checkbox-unchecked.paa);
    textureUnchecked = PATHOF(data\ui\checkbox-unchecked.paa);
};
